- implementation: nodestream_akamai.cps:AkamaiCPSExtractor
  arguments:
    base_url: !env 'base_url'
    client_token: !env 'client_token'
    client_secret: !env 'client_secret'
    access_token: !env 'access_token'
    account_key: !env 'account_key'
  annotations:
  - live
  - test
- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
    - type: source_node
      node_type: akamai_certificate
      normalization:
        do_remove_trailing_dots: true
      key:
        id: !jmespath 'id'
    - type: properties
      properties:
        expiry: !jmespath 'expiry'
        cn: !jmespath 'csr.cn'
    - type: relationship
      node_type: endpoint
      node_key: 
        fqdn: !jmespath 'csr.cn'
      relationship_type: PROTECTED_BY
      outbound: false
    - type: relationship
      node_type: endpoint
      node_key: 
        fqdn: !jmespath 'csr.sans[*]'
      relationship_type: PROTECTED_BY
      outbound: false

- implementation: nodestream.databases:GraphDatabaseWriter
  arguments:
    batch_size: !env NEO4J_BATCH_SIZE
    database: neo4j
    uri: !env NEO4J_ENDPOINT
    username: !env NEO4J_DATABASE_USERNAME
    password: !env NEO4J_DATABASE_PASSWORD