name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'poetry'
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          poetry env use "3.11"
          poetry install
      - name: Run Lints
        run: |
          poetry run ruff nodestream_akamai
          poetry run black nodestream_akamai --check
          poetry run isort nodestream_akamai --check-only
